# Generated by Django 2.1.2 on 2018-11-11 12:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
