# Generated by Django 2.1.2 on 2018-10-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20181016_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='solved',
        ),
        migrations.AlterField(
            model_name='solves',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to='challenges.Challenge'),
        ),
    ]
