# Generated by Django 2.1.2 on 2018-10-17 21:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20181016_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solves',
            name='create_at',
        ),
        migrations.AddField(
            model_name='solves',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solves',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
    ]
