# Generated by Django 2.1.2 on 2018-11-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_badsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
