# Generated by Django 2.1.2 on 2018-11-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20181118_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
