# Generated by Django 2.1.2 on 2018-11-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solves',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solves',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='challenges.Challenge'),
        ),
    ]
