# Generated by Django 2.1.2 on 2018-11-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
