# Generated by Django 2.1.2 on 2018-10-31 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_ctf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctf',
            name='ctf',
        ),
        migrations.DeleteModel(
            name='CTF',
        ),
    ]
